In [1]:
import numpy as np
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [3]:
data=pd.read_csv("/content/drive/MyDrive/ian/Boston.csv")

In [4]:
data

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  rad  \
0             1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1   
1             2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2   
2             3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2   
3             4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3   
4             5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3   
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...   
501         502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1   
502         503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1   
503         504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1   
504         505  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1   
505         506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1   

     tax  ptratio   black  lstat  medv  
0    296     15.3  396.90   4.98  24.0  
1    242     17.8  396.90   9.14  21.6  
2    242     17.8  392.83   4.03  34.7  
3    222     18.7  394.63   2.94  33.4  
4    222     18.7  396.90   5.33  36.2  
..   ...      ...     ...    ...   ...  
501  273     21.0  391.99   9.67  22.4  
502  273     21.0  396.90   9.08  20.6  
503  273     21.0  396.90   5.64  23.9  
504  273     21.0  393.45   6.48  22.0  
505  273     21.0  396.90   7.88  11.9  

[506 rows x 15 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  506 non-null    int64  
 1   crim        506 non-null    float64
 2   zn          506 non-null    float64
 3   indus       506 non-null    float64
 4   chas        506 non-null    int64  
 5   nox         506 non-null    float64
 6   rm          506 non-null    float64
 7   age         506 non-null    float64
 8   dis         506 non-null    float64
 9   rad         506 non-null    int64  
 10  tax         506 non-null    int64  
 11  ptratio     506 non-null    float64
 12  black       506 non-null    float64
 13  lstat       506 non-null    float64
 14  medv        506 non-null    float64
dtypes: float64(11), int64(4)
memory usage: 59.4 KB


In [6]:
data=data.replace(np.nan,0)

In [7]:
# check missing values in variables

data.isnull().sum()

Unnamed: 0    0
crim          0
zn            0
indus         0
chas          0
nox           0
rm            0
age           0
dis           0
rad           0
tax           0
ptratio       0
black         0
lstat         0
medv          0
dtype: int64

In [8]:
data.columns

Index(['Unnamed: 0', 'crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis',
       'rad', 'tax', 'ptratio', 'black', 'lstat', 'medv'],
      dtype='object')

In [9]:
X = data.drop(['rad'], axis=1)  # drop rad column and include all other rad
y = data['rad'] #  only rad is included #iloc ,x(rad,age)

In [10]:
X

Unnamed: 0     crim    zn  indus  chas    nox     rm   age     dis  tax  \
0             1  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900  296   
1             2  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671  242   
2             3  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671  242   
3             4  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622  222   
4             5  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622  222   
..          ...      ...   ...    ...   ...    ...    ...   ...     ...  ...   
501         502  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786  273   
502         503  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875  273   
503         504  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675  273   
504         505  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889  273   
505         506  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050  273   

     ptratio   black  lstat  medv  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [11]:
y

0      1
1      2
2      2
3      3
4      3
      ..
501    1
502    1
503    1
504    1
505    1
Name: rad, Length: 506, dtype: int64

In [12]:

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [13]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [14]:
# instantiate the DecisionTreeClassifier model with criterion gini index

from sklearn.tree import DecisionTreeClassifier

In [15]:
dtc=DecisionTreeClassifier(criterion='gini',random_state=0)
dtc.fit(X_train,y_train)

DecisionTreeClassifier(random_state=0)

In [16]:
y_pred = dtc.predict(X_test)

In [17]:
from sklearn.metrics import accuracy_score

print('Model accuracy score of dtc: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score of dtc: 0.8683


In [18]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix of dtc\n\n', cm)

Confusion matrix of dtc

 [[ 3  0  0  1  1  0  0  0  0]
 [ 1  3  0  1  0  0  0  0  0]
 [ 1  0 13  0  0  0  0  0  0]
 [ 3  0  0 35  6  0  0  0  0]
 [ 0  1  1  5 29  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  1  3  0  0]
 [ 0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0 45]]


In [19]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix of dtc\n\n', cm)

Confusion matrix of dtc

 [[ 3  0  0  1  1  0  0  0  0]
 [ 1  3  0  1  0  0  0  0  0]
 [ 1  0 13  0  0  0  0  0  0]
 [ 3  0  0 35  6  0  0  0  0]
 [ 0  1  1  5 29  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  1  3  0  0]
 [ 0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0 45]]


In [20]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix of dtc\n\n', cm)

Confusion matrix of dtc

 [[ 3  0  0  1  1  0  0  0  0]
 [ 1  3  0  1  0  0  0  0  0]
 [ 1  0 13  0  0  0  0  0  0]
 [ 3  0  0 35  6  0  0  0  0]
 [ 0  1  1  5 29  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  1  3  0  0]
 [ 0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0 45]]


Random Forest Classifier

In [21]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100)
rfc.fit(X_train,y_train)

RandomForestClassifier()

In [22]:
y_pred = rfc.predict(X_test)

In [23]:
from sklearn.metrics import accuracy_score

print('Model accuracy score of rfc: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score of rfc: 0.9581


In [24]:
# Print the Confusion Matrix and slice it into four pieces

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)

print('Confusion matrix of dtc\n\n', cm)

Confusion matrix of dtc

 [[ 4  0  0  0  1  0  0  0  0]
 [ 0  4  0  1  0  0  0  0  0]
 [ 0  0 14  0  0  0  0  0  0]
 [ 0  3  0 41  0  0  0  0  0]
 [ 0  1  1  0 34  0  0  0  0]
 [ 0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  4  0  0]
 [ 0  0  0  0  0  0  0  6  0]
 [ 0  0  0  0  0  0  0  0 45]]


In [25]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       1.00      0.80      0.89         5
           2       0.50      0.80      0.62         5
           3       0.93      1.00      0.97        14
           4       0.98      0.93      0.95        44
           5       0.97      0.94      0.96        36
           6       1.00      1.00      1.00         8
           7       1.00      1.00      1.00         4
           8       1.00      1.00      1.00         6
          24       1.00      1.00      1.00        45

    accuracy                           0.96       167
   macro avg       0.93      0.94      0.93       167
weighted avg       0.97      0.96      0.96       167



SVM

In [26]:
from sklearn.svm import SVC
svm=SVC()
svm.fit(X_train,y_train)

SVC()

In [27]:
y_pred=svm.predict(X_train)

LINEAR REGRESSION

In [28]:
from sklearn.linear_model import LinearRegression

In [29]:
LR=LinearRegression()

In [30]:
LR.fit(X_train,y_train)

LinearRegression()

In [31]:
y_pred=LR.predict(X_test)

In [32]:
LR=SVC(kernel="linear")

In [33]:
from sklearn.neighbors import KNeighborsClassifier

In [35]:
KN=KNeighborsClassifier(n_neighbors=8)

In [36]:
KN.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=8)

In [37]:
KN.predict(X_test)

array([ 5,  8, 24,  3, 24,  6,  4,  4, 24,  4,  8,  5, 24,  4,  4, 24,  2,
       24,  2, 24,  4,  7,  4,  1, 24, 24,  4, 24,  8,  6,  5,  5, 24, 24,
       24,  5,  2,  5,  8,  3,  6,  7,  2,  4,  2, 24,  4,  3, 24,  2,  5,
        5,  4,  5,  5, 24, 24,  4,  3,  7,  4,  3,  4,  4,  1,  8, 24,  4,
        4, 24,  3, 24, 24,  1,  5, 24,  5,  2, 24, 24,  4, 24,  1, 24,  4,
        8, 24,  5,  4,  4,  5, 24,  4,  5, 24,  4, 24, 24, 24, 24,  5,  4,
       24,  4,  6, 24,  4,  5,  5,  1, 24, 24,  5,  8,  8, 24,  8,  4,  6,
        6,  7,  7, 24,  6,  4,  5,  6,  8,  5,  8,  2,  4,  4,  6,  5, 24,
        5,  2,  5,  4,  4,  1,  1,  8, 24,  4,  5, 24,  4,  8, 24, 24,  3,
        6,  3,  5, 24, 24,  3, 24,  8,  4,  5,  5,  5,  4,  5])

In [38]:
y_pred=KN.predict(X_test)

In [39]:
KN.predict(X_test,)

array([ 5,  8, 24,  3, 24,  6,  4,  4, 24,  4,  8,  5, 24,  4,  4, 24,  2,
       24,  2, 24,  4,  7,  4,  1, 24, 24,  4, 24,  8,  6,  5,  5, 24, 24,
       24,  5,  2,  5,  8,  3,  6,  7,  2,  4,  2, 24,  4,  3, 24,  2,  5,
        5,  4,  5,  5, 24, 24,  4,  3,  7,  4,  3,  4,  4,  1,  8, 24,  4,
        4, 24,  3, 24, 24,  1,  5, 24,  5,  2, 24, 24,  4, 24,  1, 24,  4,
        8, 24,  5,  4,  4,  5, 24,  4,  5, 24,  4, 24, 24, 24, 24,  5,  4,
       24,  4,  6, 24,  4,  5,  5,  1, 24, 24,  5,  8,  8, 24,  8,  4,  6,
        6,  7,  7, 24,  6,  4,  5,  6,  8,  5,  8,  2,  4,  4,  6,  5, 24,
        5,  2,  5,  4,  4,  1,  1,  8, 24,  4,  5, 24,  4,  8, 24, 24,  3,
        6,  3,  5, 24, 24,  3, 24,  8,  4,  5,  5,  5,  4,  5])

In [40]:
y_pred=KN.predict(X_test)

In [41]:
KN=SVC(kernel="linear")

In [42]:
from sklearn.metrics import accuracy_score

print('Model accuracy score of lr: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score of lr: 0.7246


In [ ]:
NAIVE BAYES

In [43]:
from sklearn.naive_bayes import GaussianNB

In [44]:
NB=GaussianNB()

In [45]:
NB.fit(X_train,y_train)

GaussianNB()

In [46]:
y_pred=NB.predict(X_test)

In [47]:
y_pred=NB.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score

print('Model accuracy score of lr: {0:0.4f}'. format(accuracy_score(y_test, y_pred)))

Model accuracy score of lr: 0.5329
